general:
  output_dir: "" #ends with a "/"
  delete_after_record: true
transaction:
  path_to_robonomics_file: "" #where lies the binaty file, ends with a binary filename
  remote: '' #e.g. ws://127.0.0.1:9944
camera:
  ip: ''
  port: ''
  login: ''
  password: ''
  address: '' #address in parachain network
  key: '' #secret key in robonomics network
  framerate: 50 #for recording
pinata:
  enable: true
  pinata_api: ""
  pinata_secret_api: ""
ipfs:
  enable: true
datalog:
  enable: true
