general:
  output_dir: "" #ends with a "/"
  num_cams: 3 #must match with camerai number
  mode: 'record' # 'stream' or 'record'
transaction:
  path_to_robonomics_file: "" #where lies the binary file
camera0:
  enable: true
  ip: ''
  port: ''
  login: ''
  password: ''
  address: '' #address in parachain network
  framerate: 50 #for recording
camera1:
  enable: true
  ip: ''
  port: ''
  login: ''
  password: ''
  address: '' #address in parachain network
  framerate: 50 #for recording
camera2:
  enable: true
  ip: ''
  port: '554'
  login: ''
  password: ''
  address: '' #address in parachain network
  framerate: 50 #for recording
ipfs:
  enable: false
  ipfs_provider: ""
datalog:
  enable: false
  path_to_robonomics_file: ""
  suri: ""
  remote: ""
