general:
  output_dir: "/home/patara/cameras_robonomics/output/" #ends with a "/"
  num_cams: 3 #must mathc with camerai number
transaction:
  path_to_robonomics_file: "/home/patara" #where lies the binaty file
camera0:
  enable: true
  ip: '192.168.100.76'
  port: '554'
  login: 'admin'
  password: 'qwerty12345'
  address: '5EEh5TVoZtyQfnp8cZToFg5eJLWuUc5BsMFuR3nisb96r4ze' #address in parachain network
  framerate: 50 #for recording
camera1:
  enable: true
  ip: '192.168.100.58'
  port: '554'
  login: 'admin'
  password: 'qwerty12345'
  address: '5HT6UFb6tB2rYS6ue8V8BeBU9eY7HXu8pw4fGQGTN4Xrbm9X' #address in parachain network
  framerate: 50 #for recording
camera2:
  enable: false
  ip: '192.168.100.78'
  port: '554'
  login: 'admin'
  password: 'qwerty12345'
  address: '5GTjfZBoLd1C2rjjfv71uEEiDACyr9MAV3ZjoKga1T7mVRTN' #address in parachain network
  framerate: 50 #for recording
ipfs:
  enable: false
  ipfs_provider: ""
datalog:
  enable: false
  path_to_robonomics_file: ""
  suri: ""
  remote: ""
