general:
  output_dir: "" #ends with a "/"
  num_cams: 3 #must mathc with camerai number
  delete_after_record: true
transaction:
  path_to_robonomics_file: "" #where lies the binaty file
  #remote: ''
camera0:
  enable: true
  ip: ''
  port: ''
  login: ''
  password: ''
  address: '' #address in parachain network
  key: '' #secret key in robonomics network
  framerate: 50 #for recording
camera1:
  enable: true
  ip: ''
  port: ''
  login: ''
  password: ''
  address: '' #address in parachain network
  key: '' #secret key in robonomics network
  framerate: 50 #for recording
camera2:
  enable: true
  ip: ''
  port: ''
  login: ''
  password: ''
  address: '' #address in parachain network
  key: '' #secret key in robonomics network
  framerate: 50 #for recording
ipfs:
  enable: true
  #ipfs_provider: ""
datalog:
  enable: true
  #remote: ""
